FROM node:14-alpine AS builder
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install
# Copy app files
COPY . .
# Build the app
# RUN yarn build
# EXPOSE 3000
# Start the app
CMD [ "yarn", "start" ]

